{% set name = "casefy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/casefy-{{ version }}.tar.gz
  sha256: 849d6e0f80506fac70ab8e18999a4ca1eb7d8f70941682383d64aa22a7497f8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - casefy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dmlls/python-casefy
  doc_url: https://dmlls.github.io/python-casefy/
  summary: Utilities for string case conversion.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
