{% set name = "casefy" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/casefy-{{ version }}.tar.gz
  sha256: 6accce985a64b9edb2a610a29ac489d78fac80e52ff8f2d137e294f2f92b8027

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
  run:
    - python >=3.6

test:
  imports:
    - casefy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmlls/python-casefy
  doc_url: https://dmlls.github.io/python-casefy/
  summary: Utilities for string case conversion.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
